name: PHP Composer & PHPUnit

on: [push, pull_request]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: mattiasgeniar/php73

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      working-directory: ${{ github.workspace }}/o-foot
      run: composer validate

    - name: Install composer dependencies
      working-directory: ${{ github.workspace }}/o-foot
      run: composer install --prefer-dist --no-scripts -q -o;

    - name: Compile assets
      working-directory: ${{ github.workspace }}/o-foot
      run: |
        yarn install --pure-lockfile
        yarn encore production --progress false

    - name: Run Tests
      working-directory: ${{ github.workspace }}/o-foot
      run: bin/phpunit -c phpunit.xml tests/