name: PHP Composer & PHPUnit

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: mattiasgeniar/php73

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run:
        cd o-foot/
        composer validate

    - name: Install composer dependencies
      run: |
        composer install --prefer-dist --no-scripts -q -o;

    - name: Compile assets
      run: |
        yarn install --pure-lockfile
        yarn run production --progress false

    - name: Set custom php.ini settings
      run: echo 'short_open_tag=off' >> /usr/local/etc/php/php.ini

    - name: Run Tests
      run: vendor/bin/phpunit tests/
